# Generated by Django 5.2 on 2025-06-25 17:15

import app_fun4all.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('luogo', models.CharField(max_length=100)),
                ('capienza', models.PositiveIntegerField()),
                ('costo', models.PositiveIntegerField()),
                ('data_appertura', models.DateField(unique=True, validators=[app_fun4all.models.valida_data_2025])),
                ('data_chiusura', models.DateField(unique=True, validators=[app_fun4all.models.valida_data_2025])),
                ('stato', models.CharField(choices=[('A', 'Attivo'), ('I', 'Inattivo')], default='A', max_length=1)),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descrizione', models.CharField(help_text="Descrizione dell'evento", max_length=300)),
                ('data_evento', models.DateField(unique=True, validators=[app_fun4all.models.valida_data_2025])),
                ('costo', models.PositiveIntegerField(verbose_name='Costo unitario (€)')),
                ('stato', models.CharField(choices=[('A', 'Attivo'), ('C', "Cancellato dall'organizzatore"), ('S', 'Sospeso per indisponibilità della location'), ('F', 'Scaduto e precedente attivo'), ('D', 'Scaduto e precededente cancellato')], default='A', max_length=1)),
                ('organizzatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_fun4all.location')),
            ],
            options={
                'verbose_name_plural': 'Eventi',
                'ordering': ['data_evento'],
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('numero_biglietti', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('stato', models.CharField(choices=[('A', 'Attiva'), ('U', "Cancellata dall'utente"), ('C', "Cancellata come conseguenza della cancellazione dell'evento"), ('B', "Scaduta e precedentemente cancellata dall'utente"), ('S', "In sospeso poiché l'evento è in sospeso"), ('V', 'Scaduta e precedentemente cancellata da utente'), ('D', 'Scaduta e precedentemente cancellata causa evento cancellato'), ('J', 'Scaduta essendo in sopseso')], default='A', max_length=1)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_fun4all.evento')),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prenotazioni',
                'ordering': ['-data'],
            },
        ),
    ]
