# Generated by Django 5.2 on 2026-02-06 16:11

import app_fun4all.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFittizia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fittizia', models.DateField(validators=[app_fun4all.models.valida_data_2025])),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data Fittizia',
                'permissions': (('can_manage_data_fittizia', 'Can manage Data Fittizia'),),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('luogo', models.CharField(max_length=100)),
                ('capienza', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('costo', models.PositiveIntegerField()),
                ('data_apertura', models.DateField(validators=[app_fun4all.models.valida_data_2025])),
                ('data_chiusura', models.DateField(validators=[app_fun4all.models.valida_data_2025])),
                ('stato', models.CharField(choices=[('A', 'Attivo'), ('I', 'Inattivo')], default='A', max_length=1)),
                ('data_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='app_fun4all.datafittizia')),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'permissions': (('can_manage_location', 'Can manage location'),),
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descrizione', models.CharField(max_length=300)),
                ('data_evento', models.DateField(unique=True, validators=[app_fun4all.models.valida_data_2025])),
                ('costo', models.PositiveIntegerField()),
                ('stato', models.CharField(choices=[('A', 'Attivo'), ('C', "Cancellato dall'organizzatore"), ('S', 'Sospeso per indisponibilità della location'), ('F', 'Scaduto e precedente attivo'), ('D', 'Scaduto e precededente cancellato')], default='A', max_length=1)),
                ('data_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='app_fun4all.datafittizia')),
                ('organizzatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi', to='app_fun4all.location')),
            ],
            options={
                'verbose_name_plural': 'Eventi',
                'permissions': (('can_manage_evento', 'Can manage evento'),),
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_biglietti', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('A', 'Attiva'), ('U', 'Cancellata dal fruitore'), ('C', "Cancellata come conseguenza della cancellazione dell'evento"), ('B', 'Scaduta e precedentemente attiva'), ('S', "In sospeso poiché l'evento è in sospeso"), ('V', 'Scaduta e precedentemente cancellata da fruitore'), ('D', 'Scaduta e precedentemente cancellata causa evento cancellato'), ('J', 'Scaduta essendo in sospeso')], default='A', max_length=1)),
                ('data_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to='app_fun4all.datafittizia')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenotazioni', to='app_fun4all.evento')),
                ('fruitore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenotazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prenotazioni',
                'permissions': (('can_manage_prenotazione', 'Can manage prenotazione'),),
            },
        ),
    ]
