# Generated by Django 5.2 on 2025-11-06 14:03

import app_fun4all.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFittizia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fittizia', models.DateField(validators=[app_fun4all.models.valida_data_2025])),
            ],
            options={
                'verbose_name_plural': 'Data Fittizia',
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='data_appertura',
            field=models.DateField(validators=[app_fun4all.models.valida_data_2025]),
        ),
        migrations.AlterField(
            model_name='location',
            name='data_chiusura',
            field=models.DateField(validators=[app_fun4all.models.valida_data_2025]),
        ),
    ]
