# Generated by Django 5.2 on 2025-11-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0002_datafittizia_alter_location_data_appertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_corrente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_fun4all.datafittizia'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='data_corrente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_fun4all.datafittizia'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('A', 'Attiva'), ('U', "Cancellata dall'utente"), ('C', "Cancellata come conseguenza della cancellazione dell'evento"), ('B', 'Scaduta e precedentemente attiva'), ('S', "In sospeso poiché l'evento è in sospeso"), ('V', 'Scaduta e precedentemente cancellata da utente'), ('D', 'Scaduta e precedentemente cancellata causa evento cancellato'), ('J', 'Scaduta essendo in sospeso')], default='A', max_length=1),
        ),
    ]
