# Generated by Django 5.2 on 2025-11-07 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0003_evento_data_corrente_prenotazione_data_corrente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi', to='app_fun4all.location'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenotazioni', to='app_fun4all.evento'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='utente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenotazioni', to=settings.AUTH_USER_MODEL),
        ),
    ]
