# Generated by Django 5.2 on 2025-11-07 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0005_alter_evento_data_corrente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi', to='app_fun4all.datafittizia'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='data_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenotazioni', to='app_fun4all.datafittizia'),
        ),
    ]
