# Generated by Django 5.2 on 2025-11-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0006_alter_evento_data_corrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='data_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='app_fun4all.datafittizia'),
        ),
    ]
