# Generated by Django 5.2 on 2025-11-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0008_alter_evento_data_corrente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_corrente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='app_fun4all.datafittizia'),
        ),
        migrations.AlterField(
            model_name='location',
            name='data_corrente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='app_fun4all.datafittizia'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='data_corrente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to='app_fun4all.datafittizia'),
        ),
    ]
