# Generated by Django 5.2 on 2025-11-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0009_alter_evento_data_corrente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='data_appertura',
            new_name='data_apertura',
        ),
    ]
