# Generated by Django 5.2 on 2025-11-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0010_rename_data_appertura_location_data_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='app_fun4all.datafittizia'),
        ),
        migrations.AlterField(
            model_name='location',
            name='data_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='app_fun4all.datafittizia'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='data_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to='app_fun4all.datafittizia'),
        ),
    ]
