# Generated by Django 5.2 on 2026-01-05 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0011_alter_evento_data_corrente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['nome'], 'permissions': (('can_manage_location', 'Can manage location'),), 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='evento',
            name='gestore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_gestiti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='fruitore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizzatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_organizzati', to=settings.AUTH_USER_MODEL),
        ),
    ]
