# Generated by Django 5.2 on 2026-01-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0014_alter_evento_options_remove_evento_gestore_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data_evento'], 'verbose_name_plural': 'Eventi'},
        ),
    ]
