# Generated by Django 5.2 on 2026-01-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0015_alter_evento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafittizia',
            options={'permissions': (('can_manage_datefittizia', 'Can manage Data Fittizia'),), 'verbose_name_plural': 'Data Fittizia'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data_evento'], 'permissions': (('can_manage_evento', 'Can manage evento'),), 'verbose_name_plural': 'Eventi'},
        ),
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'ordering': ['-data'], 'permissions': (('can_manage_prenotazione', 'Can manage prenotazione'),), 'verbose_name_plural': 'Prenotazioni'},
        ),
    ]
