# Generated by Django 5.2 on 2026-01-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0016_alter_datafittizia_options_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='fruitore',
        ),
    ]
