# Generated by Django 5.2 on 2026-01-25 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0017_remove_prenotazione_fruitore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafittizia',
            options={'permissions': (('can_manage_date_fittizia', 'Can manage Data Fittizia'),), 'verbose_name_plural': 'Data Fittizia'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='costo',
            field=models.PositiveIntegerField(help_text='€'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descrizione',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='location',
            name='capienza',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='numero_biglietti',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
