# Generated by Django 5.2 on 2026-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fun4all', '0018_alter_datafittizia_options_alter_evento_costo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenotazione',
            old_name='utente',
            new_name='fruitore',
        ),
        migrations.AlterField(
            model_name='evento',
            name='costo',
            field=models.PositiveIntegerField(),
        ),
    ]
